@extends(getTemplate().'.view.layout.layout')
@section('title')
    {{ !empty($setting['site']['site_title']) ? $setting['site']['site_title'] : '' }}
@endsection
@section('page')
    <style>
        h6{font-size:1em;font-weight:bold}
    </style>
    <div class="h-20"></div>
    <div class="container">
        <div class="light-box">
            <div class="row">
                <div class="col-xs-12">
                    <h1 class="text-center violet bold">Terms & Conditions</h1>
                    <div class="h-20"></div>
                    <p><img style="width: 100%;" src="{{url('/bin/admin/Pages/aboutus.png')}}"></p>
                    <p><br></p>
                    <h3 class="bold">Terms &amp; Conditions</h3>
                    <p align="justify">Terms and Conditions for the Purchase of Online Courses<br><br><br>Effective: 15.October 2020<br><br><br>These terms and conditions apply to Services provided by MyMoon Online Ltd (company number 12604335) of address (“My Moon Ltd” or “we” or “us”). <br><br>You may contact us on email and telephone.<br><br><br>These terms and conditions are in addition to the Website Disclaimer and apply to the sale of any Online Course. Please read these terms and conditions carefully before purchasing an Online Course and print off a copy for your records.<br><br><br>If there is any conflict between our Website Disclaimer, these terms and conditions and any Course Specific Terms and Conditions which might apply to a specific Online Course or then the conflict shall be resolved by applying the following order of priority:<br><br>&nbsp;Course Specific Terms and
                        Conditions; These Standard Terms for the Purchase of Online Course; Website Disclaimer. <br><br>For purchases via our website, by clicking on the “Purchase” button you agree to the terms of this agreement which will bind you. If you do not agree to these terms and conditions you must cease to continue to purchase any Services from us. <br><br></p><h6>1. Definitions</h6>
                    <p align="justify">“Confidential Information” means information provided by one party to the other in written, graphic, recorded, machine readable or other form concerning the business, clients, suppliers, finances and other areas of the other party’s business or products, including, without limitation, the Course Materials, but does not include information in the public domain other than through the default of the party disclosing the information, information required to be disclosed by any court or regulatory authority, or any information already in the possession or control of the disclosing party.<br>“Course Materials” means the information provided by MyMoon Online Ltd and teachers to accompany a course provided as part of the Services in hard copy or electronic form.<br>“Fees” means the fees paid by you to MyMoon Online Ltd for the Services.<br>“Intellectual
                        Property Rights” means copyright, rights in or relating to databases, patent rights, performers’ rights, designs and registered designs, trademarks, rights in or relating to Confidential Information and other intellectual property rights (registered or unregistered) throughout the world.<br>“Online Course” means the delivery by us of an online course pursuant to which you learn course materials remotely.<br>“Services” means the provision of the Online Course purchased by you through the Website or by telephone.<br>“Taught Course” means a course taught online by Teachers using our platform <br>“Website” means www.MyMoonOnline.com, “You” means the individual purchasing the Services.<br>Section 2 discusses what MyMoon Online Ltd does and does not do when providing the Site and Site Services and some of your responsibilities when using the Site to find or enter into a
                        Service Contract with a Freelancer or Client, as detailed below.<br>The Site is a marketplace where Clients and Freelance teachers can identify each other and advertise, buy, and sell Freelancer Services online. Subject to the Terms of Service, MyMoon Online Ltd provides the Site Services to Users, including hosting and maintaining the Site, facilitating the formation of Service Contracts, and assisting Users in resolving disputes which may arise in connection with those Service Contracts. When a User enters a Service Contract, the User uses the Site to invoice and pay any amounts owed under the Service Contract.<br><br></p><h6>2. Relationship with My Moon Online Ltd</h6><h6>2.1 What is My Moon Online Ltd</h6>
                    <p align="justify">MyMoon Online LTD ‘s mission is to provide worldwide access to the best Arabic, Quran courses. We believe strongly in caring free speech and expression for our users as well as academic freedom for our Teachers and Instructors. We also want to make sure that all of our users and instructors feel safe and comfortable while using our Services. We have drafted these Terms and Conditions to ensure that people understand and follow the rules when participating in our online community and otherwise using our Services.<br>MyMoon Online Ltd merely makes the MyMoon Online Ltd website and Services available to enable Teachers and Students to find and transact directly with each other. MyMoon Online Ltd is open to all regardless of their political or ethic views, religion, sexual orientation, gender, age, demography, appearance, disabilities etc. MyMoon Online
                        Ltd stands for tolerance and will not tolerant extremist ideas on its websites and online courses. Any criminal offence brought to MyMoon Online Ltd ‘s attention will be reported to the police. Students of all age can use MyMoon Online Ltd, minor students will do so under parental supervision. Each student must have a personal MyMoon Online Ltd. account.<br>MyMoon Online Ltd does not introduce Teachers to Students, find Students to teacher, or find Teachers for Students. Through MyMoon Online Ltd website and Site Services, Teachers may be notified of Students that may be seeking the services they offer, and Students may be notified of Teachers that may offer the services they are looking for; at all times, however, Users are responsible for evaluating and determining the suitability of any Project, Students or Teachers on their own. If Users decide to enter into a
                        Service Contract, the Service Contract is directly between the Users and MyMoon Online Ltd is not a party to that Service Contract.<br>You acknowledge, agree, and understand that MyMoon Online Ltd is not a party to the relationship or any dealings between Students and Teachers. Without limitation, Users are solely responsible for: <br>(a) ensuring the accuracy and legality of any User Content; <br>(b) determining the suitability of other Users for a Service Contract (such as any interviews, vetting, background checks, or similar actions); <br>(c) negotiating, agreeing to, and executing any terms or conditions of Service Contracts; <br>(d) performing the lessons; or<br>(e) paying for the lessons. You further acknowledge, agree, and understand that you are solely responsible for assessing whether to enter into a Service Contract with another User and for verifying
                        any information about another User, including Composite Information (defined below). MyMoon Online Ltd does not make any representations about or guarantee the truth or accuracy of any Teacher or Student listings or other User Content on the Site; does not verify any feedback or information provided by Users about Teachers or Students; and does not vet or otherwise perform background checks on Teachers or students. You acknowledge, agree, and understand that MyMoon Online Ltd does not, in any way, supervise, direct, control, or evaluate Teachers or their work and is not responsible for any Project, Project terms or Work Product. MyMoon Online Ltd makes no representations about and does not guarantee, and you agree not to hold My Moon Online Ltd responsible for, the quality, safety, or legality of the Teachers Services; the qualifications, background, or identities
                        of Users; the ability of Teachers to deliver lessons Services; the ability of Students to pay for Teachers Services; User Content and statements or posts made by Users; or the ability or willingness of a Student or Teacher to actually complete a transaction.<br></p>
                    <p align="justify">You also acknowledge, agree, and understand that Teachers are solely responsible for determining, and have the sole right to determine, which Students they accept; the time, place, manner, and means of providing any lessons; the type of services they provide; and the price they charge for their services or how that pricing is determined or set. Additionally, you acknowledge, agree, and understand that:<br>(i) Teachers are not employees of MyMoon Online Ltd and they are not eligible for any of the rights or benefits of employment (including unemployment and/or workers compensation insurance); <br>(ii) MyMoon Online Ltd will not have any liability or obligations, including under or related to Service Contracts and/or lessons Services for any acts or omissions by Teachers or other Users;<br>(iii) MyMoon Online Ltd does not, in any way, supervise,
                        direct, or control any Teacher or Lessons Services; does not impose quality standards or a deadline for completion of any Lessons Services; and does not dictate the performance, methods or process Teachers uses to perform services; <br>(iv) Teacher is free to determine when and if to perform a lesson, including the days worked and time periods of work, and MyMoon Online Ltd does not set or have any control over teacher’s pricing, work hours, work schedules, or work location, nor is MyMoon Online Ltd involved in any other way in determining the nature and amount of any compensation that may be charged by or paid to Teachers for a Project;<br>(v) Teachers will be paid at such times and amounts as agreed with a Student/ Client in a given Service Contract, and MyMoon Online Ltd does not, in any way, provide or guarantee Teachers a regular salary or any minimum,
                        regular payment; <br>(vi) MyMoon Online Ltd does not provide Teachers with training or any equipment, labor, tools, or materials related to any Service Contract;<br><br></p><h6>3.Policy of use </h6>
                    <p align="justify">At our discretion, we may remove or edit inappropriate content or activity identified by or reported to us or suspend, disable, or terminate a user's access to all or part of the Services.<br></p><h6>3.1 You are prohibited from using our Services to share content that:</h6>
                    <p align="justify">•&nbsp; Promote hate, terrorism, any harmful content.<br>• Contains illegal content or promotes illegal activities with the intent to commit such activities. Please keep in mind that children use MyMoon Online Ltd, and we do not allow content that is inappropriate for these younger users.<br>• Contains credible threats or organizes acts of real-world violence. We don’t allow content that creates a genuine risk of physical injury or property damage, credibly threatens people or public safety, or organizes or encourages harm.<br>• Harasses others. We encourage free speech and respect for all regardless of their age, sex, race, religion, sexual orientation etc. Abusive or otherwise inappropriate content directed at private individuals is not allowed.<br>• Violates intellectual property, privacy, or other rights. Do not share content that you do not
                        have the right to share, claim content that you did not create as your own, or otherwise infringe or misappropriate someone else’s intellectual property or other rights. Always attribute materials used or quoted by you to the original copyright owner.<br>• Spams others. Do not share irrelevant or inappropriate advertising, promotional, or solicitation content. Otherwise violates the MyMoon Online Ltd Terms and Conditions. Please note that specific Content Offerings may have additional rules and requirements. <br><br></p><h6>3.2 You also aren't allowed to:</h6>
                    <p align="justify">•&nbsp;&nbsp;&nbsp; Do anything that violates local, state, national, or international law or breaches any of your contractual obligations or fiduciary duties.<br>•&nbsp;&nbsp;&nbsp; Share your password, let anyone access your account, or o anything that might put your account at risk.<br>•&nbsp;&nbsp;&nbsp; Attempt to access any other user's account.<br>•&nbsp;&nbsp;&nbsp; Reproduce, transfer, sell, resell, or otherwise misuse any content from our Services, unless specifically authorized to do so.<br>•&nbsp;&nbsp;&nbsp; Access, interfere with, or use non-public areas of our systems, unless specifically authorized to do so. •&nbsp;&nbsp;&nbsp; Break or circumvent our authentication or security measures or otherwise test the vulnerability of our systems or networks, unless specifically authorized to do so.<br>•&nbsp;&nbsp;&nbsp; Try to reverse
                        engineer any portion of our Services.<br>•&nbsp;&nbsp;&nbsp; Try to interfere with any user, host, or network, for example by sending a virus, overloading, spamming, or mail-bombing.<br>•&nbsp;&nbsp;&nbsp; Use our Services to distribute malware.<br>•&nbsp;&nbsp;&nbsp; Use our Services or any functionality of the MyMoon Online Ltd platform for anything other than for completing online courses or for pedagogical purposes.<br>•&nbsp;&nbsp;&nbsp; Impersonate or misrepresent your affiliation with any person or entity.<br>•&nbsp;&nbsp;&nbsp; Encourage or help anyone do any of the things on this list.<br><br></p><h6>4. Refund Policy</h6>
                    <p align="justify">Effective as of 15.October 2020.<br>For details on our refund deadlines and policies, please refer to the information below. Please also note that we treat violations of our Terms and Condition very seriously, and we have no obligation to offer refunds to users who violate these terms, even if their requests are made within the designated refund period. Similarly, we have no obligation to offer late refunds to users after the first session. MyMoon Online Ltd offers first class free. Students have 14 days cooling off period. Any class booked, taken or missed after the first session is due and will not be refunded In the event you are not fully satisfied with your first lessons MyMoon Online Ltd will offer a refund upon explanation. This is only available 3 times a year / per student. <br></p><h6>4.1 Group courses</h6>
                    <p align="justify">Group classes are classes of more than one student.<br>Upon request, the first class can be refunded.<br></p><h6>4.2 Video courses:</h6>
                    <p align="justify"> Are recorded courses, uploaded by teachers. The students access the first video for free. Any further courses downloaded will not be refund.<br></p><h6>4.3 One-time Course </h6>
                    <p align="justify">Upon pre-enrolment and payment of a first course, the student will be offered a complete refund up until 14 days after the course launches. For avoidance doubt, once you have earned a Course Certificate with your payment, you are not eligible for a refund even if it is within 14 days. Notwithstanding the foregoing, shorter refund periods may apply to specific courses and Specialisations (you will only be eligible for a full refund until seven days after your payment date). In these cases, the shorter period will be stated as part of the sign-up process for the course.<br></p><h6>4.4 For Other Paid Services</h6>
                    <p align="justify">Any other request shall be reported to MyMoon Online and will be individually considered .Except as described in this Refund Policy or as explicitly stated as part of the sign-up process for a Service, My Moon Online Ltd has no obligation to provide refunds or vouchers for any other Services.<br><br></p><h6>5. Feedbacks and contents</h6>
                    <p align="justify">You hereby acknowledge and agree that students and prospect students publish and request MyMoon Online Ltd to publish on their behalf information on the Site about the teachers , such as feedback, composite feedback, geographical location, or verification of identity or credentials. However, such information is based solely on unverified data that Teachers or Clients voluntarily submit to MyMoon Online Ltd and does not constitute and will not be construed as an introduction, endorsement, or recommendation by MyMoon Online Ltd; MyMoon Online Ltd provides such information solely for the convenience of users.</p><h6 align="justify">6. Service</h6>
                    <p align="justify">6.1. A description of the Services together with the dates on which the Services will begin are available on our Website. We will provide the Services with reasonable care and skill in accordance with the description set out on the Website.<br>6.2. We reserve the right to vary or withdraw any of the Services described on the Website without notice.<br>6.3 We expect you to confirm that the Services you are purchasing will meet your needs. We do not make any guarantee to you that you will obtain a particular result, professional qualification or employment opportunity from your purchase and completion of any of the Services.<br><br></p><h6>7. Ordering Services</h6><h6>7.1. Purchasing Services via the Website</h6>
                    <p align="justify">In order to purchase any of the Services online you must register for an account with us via the Website. If you already have an account with us you can log into your account using your user name and password.<br></p><h6>7.2 Purchasing Services via the application</h6>
                    <p align="justify">To purchase a Service, via the application, please download the application from Android or app store. You do not need to have registered for an account with us to purchase any of the Services over the telephone. You must, however, register for an account with us to access your course on-line.<br></p><h6>7.3. </h6>
                    <p align="justify">When you place an order for a Service via the Website, or application you are offering to purchase the Services on these terms and conditions. MyMoon Online Ltd reserves the right to cancel or decline your order or any part of your order at any time until it has been confirmed in accordance with clause 7.5 below.<br></p><h6>7.4. </h6>
                    <p align="justify">Following receipt by us of your order for Services via the Website or on the application. we will contact you confirming receipt of your order. <br></p><h6>7.5. A legally binding agreement between us and you shall come into existence when we have:</h6>
                    <p align="justify">(a) accepted your offer to purchase Services from us by sending you an email confirming the purchase; and<br>(b) received payment of the relevant Fees from you in accordance with clause 9 below. <br></p><h6>7.6. </h6>
                    <p align="justify">Where your order consists of multiple Online Courses, each individual course will be treated by us as a separate offer to purchase. Acceptance of your offer to buy one or more courses will not be acceptance by us of your offer to purchase any other courses which make up your order.<br></p><h6>7.7.</h6>
                    <p align="justify"> MyMoon Online Ltd does not and is not responsible for booking any examination with any professional body or examination board. It is your responsibility to ensure that you book prior to the relevant closing date any exam necessary that you wish to take and which may or may not be associated with the subject matter of the Services provided to you by MyMoon Online Ltd.<br><br></p><h6>8. Cancellation and Variation</h6>
                    <p align="justify">8.1. Subject to clause 7.2 below, where we have accepted / confirmed the Services being purchased by you and formed a legally binding agreement with you in accordance with clause 6.5 above, then you are permitted within 14 working days starting on the day after the date we have concluded our agreement in accordance with clause 6.4, to cancel your purchase of the Services.<br>8.2. If you have purchased an Online Course and have already accessed, downloaded all or part of the Online Course and/or started to use that Online Course then you shall have no right to cancel your order.<br>8.3. Notwithstanding clause 6.1 there is no other right to cancel or vary your purchase of Services and any other cancellation and / or variation of course dates will be at the entire discretion of MyMoon Online Ltd.<br><br></p><h6>9. Fees</h6>
                    <p align="justify">9.1. The Fees for the Services shall be as set out on the Website or as stated on the application at the time you placed an order for them.<br>9.2. Unless otherwise specified at the time you purchase the Services the Fees are exclusive of VAT or other local taxes.<br>9.3. Fees for the Service selected by you on the Website or purchased over the telephone shall be debited from your credit / debit card at the time of purchase. Fees must be paid in full prior to you accessing any Online Course.<br>9.4. Any fees charged by your debit or credit card provider in connection with your purchase of Services are for your own account and MyMoon Online Ltd shall not be responsible for these.<br>9.5. You shall be responsible for all costs you incur in connection with your access onto any Online Course.<br><br></p><h6>10. Liability</h6>
                    <p align="justify">10.1. Although MyMoon Online Ltd aims to provide the Services to the highest standards of the industry, neither it, nor its employees accept any liability for: - Any inaccuracy or misleading information provided in the programmes or course material and any reliance by Client on any such information; - Any loss or corruption of data; -Any loss of profit, revenue, or goodwill or -Any indirect, special or consequential loss arising from any breach of the terms of this Agreement.<br>Online teachers are not MyMoon Online Ltd employees.<br>10.2. Except to the extent that they are expressly set out in these terms and conditions, no conditions, warranties or other terms shall apply to the Services. Subject to clause 10.5 no implied conditions, warranties or other terms apply (including any implied terms as to satisfactory quality, fitness for purpose or
                        conformance with description).<br>10.3. Subject to clause 10.5 below, MyMoon Online Ltd's total liability arising from or in connection with these terms and conditions and in relation to anything which we may have done or not done in connection with these terms and conditions and the delivery of the Service (and whether the liability arises because of breach of contract, negligence or for any other reason) shall be limited to the Fees received by us in connection with the relevant Online Course in relation to which a dispute has arisen.<br>10.4. Nothing in this Agreement shall exclude or limit MyMoon Online Ltd’s liability for: -Death or personal injury caused by negligence;<br>-Fraudulent misrepresentation or -Any other matter which under English law may not be limited or excluded. 10.5. No claim may be brought more than three months after the last date on which
                        the Services concerned have finished or ceased to be provided by us.<br><br></p><h6>11. Intellectual Property</h6>
                    <p align="justify">11.2. Unless expressly specified you are not authorised to:<br> •&nbsp;&nbsp;&nbsp; copy, modify, reproduce, re-publish, sub-licence, sell, upload, broadcast, post, transmit or distribute any of the My Moon Online Ltd material courses and content without prior written permission;<br>•&nbsp;&nbsp;&nbsp; record on video or audio tape, relay by videophone or other means the Online Course given;<br>•&nbsp;&nbsp;&nbsp; use the Course Materials in the provision of any other course or training given by any teacher;<br>•&nbsp;&nbsp;&nbsp; modify, adapt, merge, translate, disassemble, decompile, reverse engineer ( save to the extent permitted by law) any software forming part of the Online Courses.<br>Breach by you of this clause 11.2 shall allow us to immediately terminate these terms and conditions with you and cease to provide you with any Services,
                        including but not limited to access to the Online Courses.<br>11.3. In consideration of the Fees paid by you, we grant to you a limited, non-transferable, non-exclusive licence to use the Course Materials and the software in respect of the Online Course for the sole purpose of completing the Online Course.<br><br></p><h6>12. Confidentiality</h6>
                    <p align="justify">12.1. Each party shall keep the other party’s Confidential Information strictly confidential and not use it otherwise than for the purposes of these terms and conditions and shall return it on demand and not retain copies of it.<br>12.2. Either party may disclose Confidential Information to its legal and other advisors for the purposes of obtaining advice from them.<br>12.3. This clause shall continue notwithstanding termination of these terms and conditions.<br></p><h6>13. Termination</h6>
                    <p align="justify">13.1. We shall be entitled to terminate these terms and conditions and cease to provide you with any Services with immediate effect in the event that you:<br>•&nbsp;&nbsp;&nbsp; Act in an aggressive, bullying, offensive, threatening or harassing manner towards any teacher of My Moon Online Ltd, or any student who attends any Course;<br>•&nbsp;&nbsp;&nbsp; Cheat or plagiarise any work which you are required to prepare or submit in connection with the Services or during any examination taken in connection with the Services;<br>Intentionally or recklessly damage our property or the teachers’ or other students’ properties.<br>•&nbsp;&nbsp;&nbsp; Commit any criminal offence committed on our platform or where the victim is our employee, volunteer, freelance teachers or student;<br>•&nbsp;&nbsp;&nbsp; Are in breach of these terms and conditions.<br>13.2.
                        On termination clause 10 (liability), 11 (intellectual property rights), 12 (confidentiality) shall continue notwithstanding such termination.<br><br></p><h6>14. Assignment</h6>
                    <p align="justify">Any Services provided by us under these terms and conditions are personal to you and cannot be transferred or assigned to any other person. MyMoonOnline Ltd reserve the right to assign these terms and conditions to any other company without prior notice to you.<br><br></p><h6>15. Entire Agreement</h6>
                    <p align="justify">These terms and conditions, together with the Website Disclaimer and Course Specific Terms and Conditions are the entire agreement between the parties and supersede any prior agreements and arrangements, whether written or oral. You confirm that you have not relied on any representations in entering into these and any other terms and conditions with us. Nothing in this clause or terms and conditions shall limit liability for any fraudulent misrepresentation.<br><br></p><h6>16. Force Majeure</h6>
                    <p align="justify">MyMoonOnline Ltd shall not be liable to you for any breach of its obligations or termination under these terms and conditions arising from causes beyond its reasonable control, including, but not limited to, fires, floods, earthquakes, volcanoes and other Acts of God, terrorism, strikes, delay caused by transport disputes, failure to provide a course caused by a death in the trainer’s family, illness of the trainer, Government edict or regulation.<br><br></p><h6>17. Data Protection</h6>
                    <p align="justify">17.1 The nature of the Services provided by us means that we will obtain, use and disclose (together "Use") certain information about you ("Data"). This statement sets out the principles governing our Use of Data. By purchasing the Services, you agree to this Use.<br>17.2 When you register with us you will need to provide certain Data such as your contact details and demographic information. We will store this Data and use it to contact you, provide you with details of the Services you have purchased and otherwise as required during the normal provision of the course.<br>17.3 We may also use the above Data, and similar Data you provide us in response to surveys, to aggregate user profiles and, unless you click on the relevant button on the Registration Form, provide you with communications. We will not pass any personal data onto anyone outside of
                        MyMoonOnline Ltd,<br>17.4 To enable us to monitor and improve our Services, we gather certain aggregated information about you, including details of your operating system, browser version, domain name and IP address, the URL you came from and go to and the parts of the Website you visit.<br>17.5.In line with the GDPR , we use information such as your User ID, session identifiers and password to enable us to identify whether you are using our services, assist with the provision of services and to ensure that you have access to relevant products. We will only read cookies from your cookie file placed there through your web browser's interaction with the Website.<br>17.6. Our products may link to third party websites and we are not responsible for their data policies or procedures or their content.<br>17.6. MyMoonOnline Ltd endeavour to take all reasonable steps to
                        protect your personal Data including the use of encryption technology but cannot guarantee the security of any Data you disclose. You accept the inherent security implications of being and transacting on-line over the internet and will not hold us responsible for any breach of security.<br>17.7. MyMoonOnline Ltd may supplement the information that you provide with information we receive from third parties, such as exam registration bodies or your employer.<br>17.8. If you wish to change or update the data we hold about you, please e-mail hello@mymoononline.com<br><br></p><h6>18. Law and Jurisdiction</h6>
                    <p align="justify">This Agreement is subject to English law and the parties submit to the exclusive jurisdiction of the English courts in connection with any dispute hereunder. <br><br></p><h6>19. Contact</h6>
                    <p align="justify">You can contact us by any of the following methods:<br>Email: hello@MyMoonOnline.com<br>Post: 7 Bell Yard, London, WC2A 2JR<br><br></p>


                </div>
            </div>
        </div>
        <div class="h-20"></div>
    </div>
@endsection
@section('script')
@endsection
